# Your project name will be used to name all your AWS resources.
name: mysetup

# The AWS region where you want your resources created.
region: eu-west-1

# The S3 bucket where we can store our artifacts (such as Terraform state,
# intermediate CodeBuild stages, etc). You'll have to create this bucket
# yourself in the AWS Console.
artifacts-bucket: mysetup-artifacts

billing-alarms:
  thresholds: # When your account bill reaches these specified threshold amounts
    - 120     # in USD, you will be notified by SMS using the subscriptions
    - 180     # below
  subscriptions:     # You can only subscribe using your mobile phone number.
    - "+12345678901" # That said, after the billing SNS topic is created,
    - "+10987654321" # you can add as many different subscriptions as you like,
                     # in the AWS Console, under Amazon SNS > Subscriptions

cloud9:
  - name: myproject
    instance-type: t3.small # Use any EC2 instance type you'd like

rds:
  - name: mydb
    user: root
    pass: "examplepass"
    engine: mysql
    version: "5.7" # https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html#MySQL.Concepts.VersionMgmt
    instance-type: db.t3.small # RDS supported instance types: https://aws.amazon.com/rds/instance-types/
    storage-type: gp2 # https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html
    storage-gb: 20 # Number of gigabytes you want your instance storage to be

elastic-cache:
  - name: mycache
    engine: redis
    version: 5.0.3 # https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/supported-engine-versions.html
    instance-type: cache.t2.small # EC suported instance types: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheNodes.SupportedTypes.html

s3:
  - name: mybucket
    acl: private # https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl

cloud-front:
  - name: mycdn
    bucket: mybucket
    aliases:
      - mydomain.com
    acm-certificate-arn: "arn:aws:acm:?:?:certificate/?"

route53:
  - zone: mydomain.com
    name: mysubdomain.mahdomain.com
    records:
      - 1.1.1.1
      - 1.0.0.1

orchestrations:
  - type: static-website
    zone: mydomain.com
    name: mysubdomain.mahdomain.com
    acm-certificate-arn: "arn:aws:acm:?:?:certificate/?"
    repository: mycodecommitrepo
    branch: master
